name:  dart_validation
version: 0.0.1
description: >
  A lightweight validation library in Dart.
  This package address Domain-Driven-Design,
  and validation constraints is able to place anywhere.

author: Tomochika Hara <tomochikahara@gmail.com>

dependencies:
  unittest: ">=0.3.2"
  meta: ">=0.3.2"